### PR TITLE
Centroids bugfix

### LINKED ISSUE #6: Out-of-bounds position generated by the center-of-mass centroids.
When running the full stage 2 pipeline, the SOSS extraction code crashed due to some of the y-positions found by the CoM centroids being out-of-bounds (>255 in this case). It needs to be investigated if this is a bug or not. If yes it needs fixing, if no the code needs to be made robust against out-of-bounds positions occuring.

### PR DESCRIPTION
**Pull request by radicamc**
Closes #6 

Resolves JP-

**Description**

Added new test to deal with out of bounds pixels generated by the center-of-mass centroiding algorithm. All tests were successful - e.g., a call to `Spec2Pipeline` will work now and not throw errors. 

Checklist
- [ ] Tests

- [ ] Documentation

- [ ] Change log

- [ ] Milestone

- [ ] Label(s)

### CODE REVIEW

**Review by talensgj — CHANGES_REQUESTED** [review]
Are these the right bounds checks `ycom >= dimy or ycom < 0`? Wouldn't 255.7 round to 256 in 
`irow = np.int(np.around(ycom))` and still give an error?

(Side note why is the atoca name change in this PR? Edit: Nevermind, it's spelling corrections. Fair enough)

**Comment by radicamc** [comment]
I personally think the whole section (lines 162 - 170) where we do this second test can be removed. If we're masking either the first or second order before running the centroiding algorithm, we should never really be in a position where the centroid is falling in between two equally bright orders.
But given the short timeline, its probably best to just leave it as it is, and I'll fix up the test.

**Comment by radicamc** [comment]
No idea why all these checks are failing... Everything still runs fine?

**Comment by talensgj** [comment]
The tests carried over from the main repository. I think the planned rebase should fix them.

**Review by talensgj — CHANGES_REQUESTED** [review]
I can confirm this seems to work in all my tests. @radicamc can I request that you fetch and merge initial-soss-code into this branch? It's 8 commits behind and I'd like to test it with those changes included.

**Comment by radicamc** [comment]
@talensgj Done.

**Review by talensgj — CHANGES_REQUESTED** [review]
Ok final comment. In soss_solver.py there's a duplicate numpy import.

**Comment by radicamc** [comment]
Hm, I wonder why pycharm didn't flag that. But removed now!

**Review by talensgj — APPROVED** [review]
Great!

**Pull request closed without merging**
