### PR TITLE
Implement new Tikhonov code, to be verified by Antoine.

### PR DESCRIPTION
**Pull request by talensgj**
I've copied over Antoine's revisions from jwst-mtl. I think the next steps should be as follows, and performed by @AntoineDarveau:

1. These changes should be checked.
2. The changes should be tested using a modified version of Antoine's notebook.
3. The procedural code block in `soss_extract.py` function `model_image()` line 180 `if tikfac is None:` should be updated.

Only once these steps are complete and tested can the new Tikhonov code be merged back into the main SOSS development branch via this PR.

### CODE REVIEW

**Review by AntoineDarveau — APPROVED** [review]
I've tested the changes using run_extraction.py. Everything seems fine!

**Comment by talensgj** [comment]
I had a look at the revisions and have some points to raise.

First some minor comments on the procedural code:
1. In `estim_flux_first_order` the parameter `wave_bounds` goes unused.
2. I think `estim_flux_first_order` should be made part of `engine_utils.py`
3. There should be 2 lines of whitespace after the function.

I also tried running the stage 2 pipeline. Previously, stage 2 failed due to the magnitude of the data changing in the photom step. 

When I tried running stage 2 with the new Tikhonov code I first encountered a problem in the centroids. When calling the solver, it appears that some of the centroid values were out-of-bounds (>255) causing the code to crash. I'm unsure how this can happen, but it should clearly be looked into as a separate issue.

When I circumvented the solver, the new Tikhonov works just fine with the order of magnitude change in the values caused by the photom step, but the results are still rather puzzling. It appears the photom step has a significant impact on the shape of the extracted spectrum, though I'm not clear why this happens. I will post a comparison to slack shortly.

**Comment by AntoineDarveau** [comment]
> I had a look at the revisions and have some points to raise.
> 
> First some minor comments on the procedural code:
> 
> 1. In `estim_flux_first_order` the parameter `wave_bounds` goes unused.

Oupsy

> 2. I think `estim_flux_first_order` should be made part of `engine_utils.py`

My idea was to keep soss_engine and engine_utils general, so not SOSS-specific. Since `estim_flux_first_order` is very specific to the SOSS, I think it should not be in `engine_utils.py`. Maybe in soss_utils.py?

> 3. There should be 2 lines of whitespace after the function.

Done

**Review by njcuk9999 — APPROVED** [review]
So these changes now look good - this is still flagged as "do not merge" is that still true?

**Comment by talensgj** [comment]
I think the issues revealed when running stage 2 should be addressed on as a separate issue. So this branch can be merged now that the other points have been addressed.

**Comment by njcuk9999** [comment]
agreed. @AntoineDarveau I think you will be able to merge this (or I can if you can't) - once you've confirmed you've made a note to address this issue in another branch (or tagged someone else to do this)

**Comment by talensgj** [comment]
I already made those issues. It's why I enabled the issues tab in the first place.

**Pull request merged**
